In [1]:
import pandas as pd
import numpy as np

In [3]:
ds=pd.read_csv("play_tennis.csv")
ds

outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [5]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()


In [9]:
ds['outlook']=le.fit_transform(ds.outlook)
ds['temp']=le.fit_transform(ds.temp)
ds['humidity']=le.fit_transform(ds.humidity)
ds['wind']=le.fit_transform(ds.wind)
ds['play']=le.fit_transform(ds.play)


In [13]:
x=ds.iloc[:,:4].values
print(x)


[[2 1 0 1]
 [2 1 0 0]
 [0 1 0 1]
 [1 2 0 1]
 [1 0 1 1]
 [1 0 1 0]
 [0 0 1 0]
 [2 2 0 1]
 [2 0 1 1]
 [1 2 1 1]
 [2 2 1 0]
 [0 2 0 0]
 [0 1 1 1]
 [1 2 0 0]]


In [17]:
y=ds.iloc[:,-1].values
print(y)

[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)


In [23]:
print(x_train)
print(x_test)

[[1 0 1 0]
 [0 1 0 1]
 [1 2 1 1]
 [2 2 0 1]
 [1 2 0 0]
 [0 0 1 0]
 [2 1 0 1]
 [2 2 1 0]
 [2 1 0 0]
 [1 2 0 1]
 [0 2 0 0]]
[[2 0 1 1]
 [0 1 1 1]
 [1 0 1 1]]
